name: Java with Nexus Repository 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: listing jar file
      run: |
           ls -la
           cd target && ls -la
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://nexus.cloudzenix.online/
        username: admin
        password: CloudZenix
        format: maven2
        repository: GitHub-Nexus
        coordinates: groupId=com.example artifactId=app version=1.0.0
        assets: extension=jar
        filename: target/cz-springboot-welcome.jar
        
    - name: push docker image to nexus
      run: |
           docker login -u admin -p CloudZenix ip-10-0-43-67.ec2.internal:8084
           docker build -t cz-springboot-welcome
           docker tag cz-springboot-welcome:latest 10.0.43.67:8084/repository/docker-private-repo:latest
           docker push 10.0.43.67:8084/repository/docker-private-repo:latest
#    - uses: mr-smithers-excellent/docker-build-push@v5
#      name: Build & push Docker image
#      with:
##        image: docker-private-repo/cz-springboot-welcome
 #       tags: latest
#        registry: nexus.cloudzenix.online
#        dockerfile: Dockerfile
#        username: admin
#        password: CloudZenix
