name: Nexus Repository 

on: [push]

jobs:
  push-to-Nexus:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: listing jar file
      run: |
           ls -la
           cd target && ls -la
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://ec2-44-192-85-226.compute-1.amazonaws.com:8081
        username: admin
        password: nexus
        format: maven2
        repository: github-action-maven
        coordinates: groupId=com.example artifactId=app version=1.0.0
        assets: extension=jar
        filename: target/cz-springboot-welcome.jar
        
    - name: push docker image to nexus
      run: |
           ls -la 
            sudo mv daemon.json /etc/docker/daemon.json
            sudo systemctl restart docker
            sudo systemctl status docker
            sudo docker login -u admin -p nexus ec2-44-192-85-226.compute-1.amazonaws.com:8086
            sudo docker build -t ec2-44-192-85-226.compute-1.amazonaws.com:8086/cz-springboot-welcome:latest .
            sudo docker images
            sudo docker push ec2-44-192-85-226.compute-1.amazonaws.com:8086/cz-springboot-welcome:latest
        #   docker login sudo docker login -u admin -p nexus ec2-44-192-120-3.compute-1.amazonaws.com:8086
        #   docker build -t /cz-springboot-welcome
        #   docker tag cz-springboot-welcome:latest ec2-44-192-120-3.compute-1.amazonaws.com:8086/cz-springboot-welcome:latest
        #   docker push ec2-44-192-120-3.compute-1.amazonaws.com:8086/cz-springboot-welcome:latest
#    - uses: mr-smithers-excellent/docker-build-push@v5
#      name: Build & push Docker image
#      with:
##        image: docker-private-repo/cz-springboot-welcome
 #       tags: latest
#        registry: nexus.cloudzenix.online
#        dockerfile: Dockerfile
#        username: admin
#        password: CloudZenix
