name: nexus integration 

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] 

jobs:
  build-code: 
  
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
